export const SET_GET_POKEMONS = "SET_GET_POKEMONS";
// export const LOADING_GET_POKEMONS = "LOADING_GET_POKEMONS";
export const ERROR_GET_POKEMONS = "ERROR_GET_POKEMONS";
export const SUCCESS_GET_POKEMOMS = "SUCCESS_GET_POKEMOMS";
